#!/bin/sh
# Regenerates mapgeom.h from the prototype. src/game/ is the single source of
# level design and duel numbers, so the plugin reads them at build time instead
# of carrying copies that go stale when the map is rescaled.
#
# Runs on the host, not in the build container: the build mounts cs16/ only, so
# src/ is out of reach from inside it. build.sh calls this first.
set -e
cd "$(dirname "$0")"

MAP=../../src/game/map.ts
COMBAT=../../src/game/combat.ts
ENGINE=../../src/game/engine.ts
GEN=../map/gen.ts

# `export const NAME = { x: <x>, z: <z> };` -> field $2 (1 for x, 2 for z)
point() {
	sed -n "s/^export const $1 = { x: *\([-0-9.]*\), z: *\([-0-9.]*\) *}.*/\\$2/p" "$MAP"
}

one() {
	sed -n "s/^\(export \)\{0,1\}const $2 = \([-0-9.]*\).*/\2/p" "$1"
}

HOLD_X=$(point ENEMY_HOLD 1)
HOLD_Z=$(point ENEMY_HOLD 2)
PEEK_X=$(point ENEMY_PEEK 1)
PEEK_Z=$(point ENEMY_PEEK 2)
SPAWN_X=$(point PLAYER_SPAWN 1)
SPAWN_Z=$(point PLAYER_SPAWN 2)
UNITS=$(one "$GEN" U)
ROUND=$(one "$COMBAT" ROUND_SECONDS)
FOOT_RANGE=$(one "$ENGINE" FOOTSTEP_RANGE)
FOOT_SPEED=$(one "$ENGINE" FOOTSTEP_SPEED)

for pair in "ENEMY_HOLD.x:$HOLD_X" "ENEMY_HOLD.z:$HOLD_Z" "ENEMY_PEEK.x:$PEEK_X" \
	"ENEMY_PEEK.z:$PEEK_Z" "PLAYER_SPAWN.x:$SPAWN_X" "PLAYER_SPAWN.z:$SPAWN_Z" "U:$UNITS" \
	"ROUND_SECONDS:$ROUND" "FOOTSTEP_RANGE:$FOOT_RANGE" "FOOTSTEP_SPEED:$FOOT_SPEED"; do
	case $pair in
	*:) echo "geom.sh: could not read ${pair%:*} from the prototype" >&2; exit 1 ;;
	esac
done

LANE=$(awk "BEGIN { print $SPAWN_Z - ($HOLD_Z) }")

fl() { awk "BEGIN { printf \"%.4f\", $1 }"; }
UNITS=$(fl "$UNITS"); SPAWN_X=$(fl "$SPAWN_X"); SPAWN_Z=$(fl "$SPAWN_Z"); HOLD_X=$(fl "$HOLD_X"); HOLD_Z=$(fl "$HOLD_Z"); PEEK_X=$(fl "$PEEK_X"); PEEK_Z=$(fl "$PEEK_Z")
LANE=$(fl "$LANE"); ROUND=$(fl "$ROUND"); FOOT_RANGE=$(fl "$FOOT_RANGE"); FOOT_SPEED=$(fl "$FOOT_SPEED")

cat > mapgeom.h <<EOF
// Generated by geom.sh from src/game/map.ts, src/game/combat.ts,
// src/game/engine.ts and cs16/map/gen.ts. Do not edit; run ./build.sh.
#pragma once

#define UNITS_PER_METRE (${UNITS}f)

#define PROTO_HOLD_X (${HOLD_X}f)
#define PROTO_HOLD_Y (${HOLD_Z}f)
#define PROTO_PEEK_X (${PEEK_X}f)
#define PROTO_PEEK_Y (${PEEK_Z}f)
#define PROTO_SPAWN_X ${SPAWN_X}f
#define PROTO_SPAWN_Y ${SPAWN_Z}f
#define PROTO_LANE_M (${LANE}f)

#define ROUND_SECONDS (${ROUND}f)
#define FOOTSTEP_RANGE_M (${FOOT_RANGE}f)
#define FOOTSTEP_SPEED_MPS (${FOOT_SPEED}f)
EOF

echo "geom.sh: hold ($HOLD_X, $HOLD_Z)m  peek ($PEEK_X, $PEEK_Z)m  lane ${LANE}m  round ${ROUND}s  footsteps ${FOOT_RANGE}m/${FOOT_SPEED}mps  @ $UNITS u/m"
